"""
Morning briefing email renderer and SMTP sender.
Renders both plain text and HTML; sends as multipart/alternative.
"""

import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

from .composer import BriefingReport, BriefingSection

DIVIDER = "-" * 53
HEADER = "=" * 53


class EmailError(Exception):
    pass


# ---------------------------------------------------------------------------
# Plain-text renderer
# ---------------------------------------------------------------------------

def render_plain_text(report: BriefingReport) -> str:
    lines = [
        HEADER,
        "JAX HVAC MORNING BRIEFING",
        report.date_label + "  |  Generated " + report.generated_at,
        HEADER,
    ]
    for section in report.sections:
        lines += ["", DIVIDER, section.title, DIVIDER]
        lines += section.lines
    lines += [
        "",
        HEADER,
        "Generated by hvac/briefing  |  python -m hvac.cli brief",
        HEADER,
    ]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# HTML renderer
# ---------------------------------------------------------------------------

_PRIORITY_COLORS = {
    "critical": "#c0392b",
    "high": "#e67e22",
    "medium": "#2980b9",
    "low": "#7f8c8d",
    "none": "#95a5a6",
}

_CSS = """
body { font-family: Arial, sans-serif; font-size: 13px; color: #222; background: #f5f5f5; margin: 0; padding: 16px; }
.card { background: #fff; border-radius: 6px; border: 1px solid #ddd; max-width: 680px; margin: 0 auto; padding: 0; }
.header { background: #1a3a5c; color: #fff; padding: 18px 24px; border-radius: 6px 6px 0 0; }
.header h1 { margin: 0; font-size: 18px; letter-spacing: 0.5px; }
.header .sub { margin: 4px 0 0; font-size: 12px; opacity: 0.8; }
.section { padding: 16px 24px; border-bottom: 1px solid #eee; }
.section h2 { font-size: 13px; font-weight: bold; color: #1a3a5c; text-transform: uppercase; margin: 0 0 12px; letter-spacing: 0.3px; }
.wo-card { background: #fafafa; border-left: 4px solid #ccc; border-radius: 3px; padding: 10px 12px; margin-bottom: 10px; }
.wo-title { font-weight: bold; font-size: 13px; margin: 0 0 4px; }
.wo-meta { font-size: 11px; color: #666; margin: 2px 0; }
.wo-link { font-size: 11px; }
.alarm-card { background: #fafafa; border-left: 4px solid #e74c3c; border-radius: 3px; padding: 10px 12px; margin-bottom: 10px; }
.alarm-title { font-weight: bold; font-size: 12px; margin: 0 0 3px; }
.alarm-meta { font-size: 11px; color: #666; margin: 1px 0; }
.badge { display: inline-block; color: #fff; border-radius: 3px; padding: 1px 7px; font-size: 10px; font-weight: bold; margin-right: 6px; }
.journal-block { font-size: 12px; line-height: 1.6; }
.journal-block pre { font-family: monospace; font-size: 11px; background: #f8f8f8; padding: 8px; border-radius: 3px; overflow-x: auto; white-space: pre-wrap; }
.skipped { color: #999; font-style: italic; font-size: 12px; }
.footer { padding: 12px 24px; font-size: 11px; color: #aaa; text-align: center; border-radius: 0 0 6px 6px; }
.action-needed { background: #c0392b; color: #fff; text-align: center; padding: 6px; font-size: 12px; font-weight: bold; }
"""


def _badge(color: str, text: str) -> str:
    return f'<span class="badge" style="background:{color}">{text}</span>'


def _wo_html(wos) -> str:
    if not wos:
        return '<p class="skipped">(none)</p>'
    priority_order = ["critical", "high", "medium", "low", "none"]
    sorted_wos = sorted(wos, key=lambda w: priority_order.index(w.priority or "none") if (w.priority or "none") in priority_order else 99)
    html = ""
    for wo in sorted_wos:
        color = _PRIORITY_COLORS.get(wo.priority or "none", "#95a5a6")
        badge = _badge(color, (wo.priority or "none").upper())
        assignee = wo.assignee or "Unassigned"
        due = wo.due_date[:10] if wo.due_date else "no due date"
        html += f"""
        <div class="wo-card" style="border-left-color:{color}">
          <div class="wo-title">{badge} WO #{wo.id} — {wo.title}</div>
          <div class="wo-meta">Assigned: {assignee} &nbsp;|&nbsp; Due: {due}</div>
          {"<div class='wo-meta'>Location: " + wo.location + "</div>" if wo.location else ""}
          <div class="wo-link"><a href="{wo.url}">{wo.url}</a></div>
        </div>"""
    return html


def _alarm_html(alarms) -> str:
    if not alarms:
        return '<p class="skipped">(none)</p>'
    html = ""
    for alarm in sorted(alarms, key=lambda a: a.priority):
        p = alarm.priority
        color = "#c0392b" if p <= 50 else "#e67e22" if p <= 100 else "#7f8c8d"
        badge = _badge(color, f"P-{p}")
        acked = "ACKED" if alarm.is_acked else "UNACKED"
        ts = alarm.occurred_at[:16].replace("T", " ") if alarm.occurred_at else ""
        html += f"""
        <div class="alarm-card" style="border-left-color:{color}">
          <div class="alarm-title">{badge} {alarm.alarm_message}</div>
          <div class="alarm-meta">Object: {alarm.object_name}</div>
          <div class="alarm-meta">{acked} &nbsp;|&nbsp; Occurred: {ts}</div>
          {"<div class='alarm-meta'>Area: " + alarm.area + "</div>" if alarm.area else ""}
        </div>"""
    return html


def _section_html(section: BriefingSection) -> str:
    if not section.available:
        content = f'<p class="skipped">{section.error or "Not configured"}</p>'
    else:
        raw_text = "\n".join(section.lines)
        content = f'<div class="journal-block"><pre>{raw_text}</pre></div>'
    return f"""
    <div class="section">
      <h2>{section.title}</h2>
      {content}
    </div>"""


def render_html(report: BriefingReport) -> str:
    action_banner = ""
    if report.has_critical:
        action_banner = '<div class="action-needed">ACTION NEEDED — Review critical items below</div>'

    sections_html = ""
    for section in report.sections:
        sections_html += _section_html(section)

    return f"""<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><style>{_CSS}</style></head>
<body>
<div class="card">
  <div class="header">
    <h1>JAX HVAC Morning Briefing</h1>
    <div class="sub">{report.date_label} &nbsp;|&nbsp; Generated {report.generated_at}</div>
  </div>
  {action_banner}
  {sections_html}
  <div class="footer">Generated by hvac/briefing &nbsp;|&nbsp; python -m hvac.cli brief</div>
</div>
</body>
</html>"""


# ---------------------------------------------------------------------------
# SMTP sender
# ---------------------------------------------------------------------------

def send_briefing_email(
    report: BriefingReport,
    smtp_host: str,
    smtp_port: int,
    from_addr: str,
    to_addrs: list[str],
    username: str = None,
    password: str = None,
    use_tls: bool = True,
) -> None:
    prefix = "[ACTION NEEDED] " if report.has_critical else ""
    subject = f"{prefix}HVAC Morning Briefing — {report.date_label}"

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = from_addr
    msg["To"] = ", ".join(to_addrs)

    msg.attach(MIMEText(render_plain_text(report), "plain"))
    msg.attach(MIMEText(render_html(report), "html"))

    try:
        if use_tls:
            server = smtplib.SMTP(smtp_host, smtp_port, timeout=15)
            server.starttls()
        else:
            server = smtplib.SMTP_SSL(smtp_host, smtp_port, timeout=15)
        if username and password:
            server.login(username, password)
        server.sendmail(from_addr, to_addrs, msg.as_string())
        server.quit()
    except smtplib.SMTPException as e:
        raise EmailError(f"SMTP error: {e}") from e
    except OSError as e:
        raise EmailError(f"Network error sending email: {e}") from e
